#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $RIZ_REPO == "AGORA-GANGSTERS" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0RFQURMWS1GSUdIVEVSUy9ERUFETFktU1BBTS1CT1QvYXJjaGl2ZS9tYWluLnppcA==" | base64 -d
    elif [[ $RIZ_REPO == "AGORA-GANGSTERS" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0RFQURMWS1GSUdIVEVSUy9ERUFETFktU1BBTS1CT1QvYXJjaGl2ZS9tYWluLnppcA==" | base64 -d
    elif [[ $RIZ_REPO =~ $regex ]]
    then
        if [[ $RIZ_REPO_BRANCH ]]
        then
            echo "${RIZ_REPO}/archive/${RIZ_REPO_BRANCH}.zip"
        else
            echo "${RIZ_REPO}/archive/main.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0RFQURMWS1GSUdIVEVSUy9ERUFETFktU1BBTS1CT1QvYXJjaGl2ZS9tYWluLnppcA==" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="AGORA-GANGSTERS.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    RIZPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $RIZPATH
    echo "  Starting.  AGORA GANGSTERS"
    echo "AGORA GANGSTERS"

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m AgoraProfessor
}

_set_bot
